version: '3.4'

services:
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite

  data:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    
  studentsmanager.mvc:
    container_name: studentsmanagermvc
    image: profjordanov/studentsmanagermvc:10.0
    build:
      context: .
      dockerfile: StudentsManager.Mvc/Dockerfile

  studentsmanager.spa:
    container_name: studentsmanagerspa
    image: profjordanov/studentsmanagerspa:1.0
    build:
      context: ./StudentsManager.Spa
      dockerfile: Dockerfile
